
vae:
  loss_type: vanilla
  fab_loss_type: alpha_2_div
  latent_size: 10
  use_flow: false
  use_conv: false
  lr: 1e-4
  batch_size: 28
  seed: 0
  n_samples_z_train: 10
  n_samples_z_test: 20
  ais_eval: true
  n_ais_dist: 4
  n_flow_layers: 6


train:
  n_step: 500
  eval_freq: 100


logger:
  save_path: results
#  pandas_logger:
#    save_period: 100 # how often to save the pandas dataframe as a csv
  wandb:
    name: vae_loss_type${vae.loss_type}