target:
  dim: 4
  name: many_well

flow:
  type: rnvp
  layer_nodes_per_dim: 5
  n_layers: 5
  use_exp: false  # otherwise use softplus
  layer_norm: false
  act_norm: true

fab:
  loss_type: alpha_2_div
  transition_operator:
    type: hmc_tfp
    n_inner_steps: 5
    init_step_size: 0.2 # give good step size initialisation
  n_intermediate_distributions: 4

buffer:
  use: true
  prioritised: true
  max_w_adjust: 10.0 # for prioritised replay
  n_batches_buffer_sampling: 2
  maximum_buffer_length: 1000
  min_buffer_length: 100


training:
  seed: 0
  lr: 2e-4
  max_grad_norm: 5.0
  max_grad: 100.0 # if not used can cause a weird effect where grad norm clipping causes underflow
  batch_size: 32
  n_iterations: 2_000
  use_64_bit: true



evaluation:
  n_plots: 4 # number of times we visualise the model throughout training.
  n_evals: 4 # for calculating metrics of flow w.r.t target.
  batch_size: 320 # must be a multiple of inner batch size
  n_checkpoints: null # number of model checkpoints saved
  save_path:  results/many_well32/


logger:
  pandas_logger:
    save_period: 100 # how often to save the pandas dataframe as a csv
#  wandb:
#    name: ManyWell32
#    tags: [alpha_2_loss,ManyWell32]
