target:
  name: atomic_solids
  system: mw_cubic_8

flow:
    use_default_params: false
    num_bins: 5 # default 16
    num_layers: 3 # default 26
    embedding_size: 8 # default 256

fab:
  n_intermediate_distributions: 1


buffer:
  use: true
  prioritised: true
  max_w_adjust: 100.0 # for prioritised replay
  n_batches_buffer_sampling: 4
  maximum_buffer_length: 51200
  min_buffer_length: 5120


training:
  seed: 0
  lr: 1e-4
  optimizer_type: adam # adabelief, adam
  max_grad_norm: 5.0
  max_grad: 100.0 # if not used can cause a weird effect where grad norm clipping causes underflow
  batch_size: 128
  n_iterations: 1_000
  use_64_bit: false



evaluation:
  n_plots: null # number of times we visualise the model throughout training.
  n_evals: 10 # for calculating metrics of flow w.r.t target.
  batch_size: 128 # must be a multiple of inner batch size
  n_checkpoints: null # number of model checkpoints saved
  save_path:  results/atomic_solids/


logger:
  list_logger:
    use: true
#  pandas_logger:
#    save_period: 100 # how often to save the pandas dataframe as a csv
#  wandb:
#    name: ${target.system}_TPU
#    project: fab
#    entity: flow-ais-bootstrap
#    tags: [alpha_2_loss,atomic_solids]